### ISSUE TITLE
Implement Delete Items WS

### ISSUE THREAD

**Issue by hiranwj** [Direct-Entry-Program/pos-back-end#14]
DELETE/items/{itemId}
DELETE/items/{itemId}/

{itemId} - should be valid UUID

**Successful Response**
204 Success No Content
Content-type: application/json
Returns customer object

**Failed Response**
500 - INTERNAL SERVER ERROR - sql error can not load db
501 - NOT IMPLEMENTED - invalid UUID format
404 - BAD REQUEST - UUID not saved in the db

**Comment by danulatb** [comment]
min 30
