### ISSUE TITLE
Implement Place Order WS

### ISSUE THREAD

**Issue by PubuduJ** [Direct-Entry-Program/pos-back-end#2]
POST /orders
POST /orders/

**Successful Response**
201 OK
Content type: application/json
Returns a order object

**Failed Response**
400 BAD REQUEST - the syntax of the request is wrong, client error.
422 UNPROCESSABLE ENTITY - the syntax of the request entity is correct, but it was unable to process the contained instructions.

**Comment by danulatb** [comment]
min 60
