### ISSUE TITLE
Implement Get Order Details WS

### ISSUE THREAD

**Issue by PubuduJ** [Direct-Entry-Program/pos-back-end#4]
GET /orders/{order-id}
GET /orders/{order-id}/

**Successful Response**
200 OK
Content-Type: application/json
Returns a customer object

**Failed Response**
404 NOT FOUND - If there is no match found for this {order-id}
501 NOT IMPLEMENTED - If the {order-id} is not a valid UUID or invalid URL pattern

**Comment by danulatb** [comment]
min 45
