### ISSUE TITLE
Implement Search Paginated Order WS

### ISSUE THREAD

**Issue by PubuduJ** [Direct-Entry-Program/pos-back-end#6]
GET /orders?q={query}&size={size}&page={page}
GET /orders?q={query}&size={size}&page={page}/

**Successful Response**
200 OK
Content-Type: application/json
Return orders as a json array of order objects which are matched to the {query} and {size} out of {page}

**Failed Response**
404 NOT FOUND - If there is no match found for the the {query}
501 NOT IMPLEMENTED - the server does not support the functionality required to fulfill the given request

**Comment by danulatb** [comment]
min 45
